diploiTemplateVersion: V1.0
name: diploi-nextjs-template
description: NextJS template for Diploi

stages:
  - name: Production
    label: production
  - name: Staging
    label: staging
  - name: Development
    label: development

contexts:
  - name: app
    label: app
  - name: redis
    label: redis

parameterGroups:
  - name: MySQL Database
    label: mysql
    toggleable: true
    parameters:
      - name: Host
        label: DB_HOST
        value: mysql.example.com
        type: string
      - name: Password
        label: DB_PASSWORD
        value: ''
        type: secret
  - name: Servers
    label: SERVER
    parameters:
      - name: Server count
        label: SERVER_REPLICAS
        value: 2
        type: integer
        stages:
          - production

environmentVariables:
  - name: PROJECT_TITLE
    value: ProjectTitleDefaultFromTemplate
    type: string
    selector: label=app
  - name: SOME_OTHER_SETTING
    value: asdasd
    type: string
    selector: label=app

repositories:
  - name: web
    label: web
    url: https://github.com/NemesysLtd/diploi-node-sample #optional

hosts:
  - name: App
    label: app
    url: 'www-[label].[default-domain]'

ssh:
  - username: '[label]'
    selector: label=app
    stages:
      - development
  - username: '[label]-[index]'
    selector: label=app
    stages:
      - production
  - username: '[label]-redis'
    selector: label=redis

logs:
  - name: Pod Log
    selector: label=app
  - name: API Log
    selector: label=app
    command: tail --lines 2000 -f /var/log/api.log
  - name: API Error Log
    selector: label=app
    command: tail --lines 2000 -f /var/log/api.log | grep Fatal

actions:
  - name: Restart servers
    selector: label=app
    command: npm run restart
  - name: Reinstall packages
    selector: label=app
    command: npm run clean

images:
  - label: app
    dockerfile: Dockerfile
    repository: web
    stages:
      - production
      - staging
      - development      

storage:
  - label: app
    stages: 
      - development
    sizeMb: 8000 
  - label: rootpersist
    stages: 
      - development
    sizeMb: 1000 
