diploiTemplateVersion: V1.0
name: diploi-nextjs-template
description: NextJS template for Diploi

stages:
  - name: Production
    identifier: production
  - name: Staging
    identifier: staging
  - name: Development
    identifier: development

contexts:
  - name: app
    identifier: app
  - name: redis
    identifier: redis

parameterGroups:
  - name: MySQL Database
    identifier: mysql
    toggleable: true
    parameters:
      - name: Host
        identifier: DB_HOST
        defaultValue: mysql.example.com
        type: string
      - name: Password
        identifier: DB_PASSWORD
        defaultValue: ''
        type: secret
  - name: Servers
    identifier: SERVER
    parameters:
      - name: Server count
        identifier: SERVER_REPLICAS
        defaultValue: 2
        type: integer
        stages:
          - production

environmentVariables:
  - identifier: PROJECT_TITLE
    defaultValue: ProjectTitleDefaultFromTemplate
    type: string
    contexts: label=app
  - identifier: SOME_OTHER_SETTING
    defaultValue: asdasd
    type: string
    contexts: label=app

repositories:
  - name: web
    identifier: web
    exampleProjectUrl: https://github.com/NemesysLtd/diploi-node-sample #optional

hosts:
  - name: App
    identifier: app
    urlFormat: 'www-[label].[default-domain]'

ssh:
  - usernameFormat: '[label]'
    contexts: label=app
    stages:
      - development
  - usernameFormat: '[label]-[index]'
    contexts: label=app
    stages:
      - production
  - usernameFormat: '[label]-redis'
    contexts: label=redis

logs:
  - name: Pod Log
    contexts: label=app
  - name: API Log
    contexts: label=app
    command: tail --lines 2000 -f /var/log/api.log
  - name: API Error Log
    contexts: label=app
    command: tail --lines 2000 -f /var/log/api.log | grep Fatal

actions:
  - name: Restart servers
    contexts: label=app
    command: npm run restart
  - name: Reinstall packages
    contexts: label=app
    command: npm run clean

images:
  - identifier: app
    baseImageDockerfile: Dockerfile
    repository: web
    stages:
      - production
      - staging
      - development      

storage:
  - identifier: app
    stages: 
      - development
    sizeMb: 8000 
  - identifier: rootpersist
    stages: 
      - development
    sizeMb: 1000 
