label: app
hostname: diploi.test.nemesys.fi
apiHostname: diploi.test.nemesys.fi
appMount: pvc-app-code

dockerRegistry:
  hostname: 'https://index.docker.io/v1/'
  username: 'nemesys'
  password: ''
  email: ''
