apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disabled
  labels:
    app: disabled
spec:
  selector:
    matchLabels:
      app: disabled
  serviceName: disabled
  replicas: {{ ternary 0 1 .Values.enabled }}
  template:
    metadata:
      labels:
        app: disabled
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: disabled
          image: nginxdemos/hello
          ports:
            - containerPort: 80
         
        
