apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0.6-alpine
          imagePullPolicy: Always
          args:
            - '--requirepass'
            - '$(REDIS_PASS)'
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASS
              value: xxxyyy
#            {{- range .Values.env }}
#            {{- if contains "redis" .selector }}
#            - name: {{ .name }}
#              value: {{ .value | quote }}
#            {{- end }}
#            {{- end }}
